In [1]:
import pandas as pd

In [2]:
f = '/u/home/f/f7xiesnm/project-zipursky/v1-bb/v1/data/allen_yao23/yao23_donor_table.csv'
df0 = pd.read_csv(f)
df0

,external_donor_name,full_genotype,sex,cycle,assay,age,n_cells_preQC,n_cells_postQC,roi_1,roi_2,roi_3,roi_4,facs_population_plan_1,facs_population_plan_2,facs_population_plan_3,facs_population_plan_4
0,352353,Snap25-IRES2-Cre/wt;Ai14(RCL-tdT)/wt,M,Light,10Xv2,57 days,50543,43370,MOp,NaN,NaN,NaN,RFP-positive,NaN,NaN,NaN
1,352356,Snap25-IRES2-Cre/wt;Ai14(RCL-tdT)/wt,M,Light,10Xv2,57 days,42687,36274,MOp,NaN,NaN,NaN,RFP-positive,NaN,NaN,NaN
2,352357,Snap25-IRES2-Cre/wt;Ai14(RCL-tdT)/wt,M,Light,10Xv2,58 days,52687,43515,MOp,NaN,NaN,NaN,RFP-positive,NaN,NaN,NaN
3,355877,Snap25-IRES2-Cre/wt;Ai14(RCL-tdT)/wt,M,Light,10Xv2,58 days,14636,7788,VISa,VISpos,NaN,NaN,RFP-positive,RFP-positive,NaN,NaN
4,355878,Snap25-IRES2-Cre/wt;Ai14(RCL-tdT)/wt,M,Light,10Xv2,59 days,42705,36206,VISl,VISm,VISp,NaN,RFP-positive,RFP-positive,RFP-positive,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,613581,Snap25-IRES2-Cre/wt;Ai14(RCL-tdT)/wt,F,Light,10Xv3,57 days,8763,3310,MY - CN-DCN-ECU-NTS-SPVC-SPVI-SPVO,NaN,NaN,NaN,"RFP-positive, DAPI-negative",NaN,NaN,NaN
313,618176,Snap25-IRES2-Cre/wt;Ai14(RCL-tdT)/wt,M,Light,10Xv3,65 days,5338,3125,HY - MEZ-PVZ-PVR,NaN,NaN,NaN,"RFP-positive, DAPI-negative",NaN,NaN,NaN
314,619870,Snap25-IRES2-Cre/wt;Ai14(RCL-tdT)/wt,F,Light,10Xv3,60 days,24854,11644,AI-CLA,HY - MEZ-PVZ-PVR,NaN,NaN,"RFP-positive, DAPI-negative","RFP-positive, DAPI-negative",NaN,NaN
315,621073,Snap25-IRES2-Cre/wt;Ai14(RCL-tdT)/wt,M,Light,10Xv3,58 days,10611,7194,MB-PONS - DR-PPN-SOC-V,MB-PONS - DR-PPN-SOC-V,NaN,NaN,No FACS,"RFP-positive, DAPI-negative",NaN,NaN
316,621471,Snap25-IRES2-Cre/wt;Ai14(RCL-tdT)/wt,F,Light,10Xv3,66 days,7976,4765,PL-ILA-ORB,NaN,NaN,NaN,"RFP-positive, DAPI-negative",NaN,NaN,NaN

In [30]:
%%time
f    = '/u/home/f/f7xiesnm/project-zipursky/v1-bb/v1/data/allen_yao23/cell_metadata_with_cluster_annotation.csv.gz'
fout = '/u/home/f/f7xiesnm/project-zipursky/v1-bb/v1/data/allen_yao23/cell_metadata_with_cluster_annotation_l23_vis_ptlp.csv'
df = pd.read_csv(f)
df

<timed exec>:3: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.

CPU times: user 21.7 s, sys: 4.54 s, total: 26.3 s
Wall time: 26.3 s

,cell_label,cell_barcode,barcoded_cell_sample_label,library_label,feature_matrix_label,entity,brain_section_label,library_method,region_of_interest_acronym,donor_label,...,subclass,supertype,cluster,neurotransmitter_color,class_color,subclass_color,supertype_color,cluster_color,region_of_interest_order,region_of_interest_color
0,GCGAGAAGTTAAGGGC-410_B05,GCGAGAAGTTAAGGGC,410_B05,L8TX_201030_01_C12,WMB-10Xv3-HPF,cell,NaN,10Xv3,RHP,Snap25-IRES2-Cre;Ai14-550850,...,018 L2 IT PPP-APr Glut,0082 L2 IT PPP-APr Glut_3,0326 L2 IT PPP-APr Glut_3,#2B93DF,#FA0087,#0F6632,#266DFF,#64661F,15,#CCB05C
1,AATGGCTCAGCTCCTT-411_B06,AATGGCTCAGCTCCTT,411_B06,L8TX_201029_01_E10,WMB-10Xv3-HPF,cell,NaN,10Xv3,RHP,Snap25-IRES2-Cre;Ai14-550851,...,018 L2 IT PPP-APr Glut,0082 L2 IT PPP-APr Glut_3,0326 L2 IT PPP-APr Glut_3,#2B93DF,#FA0087,#0F6632,#266DFF,#64661F,15,#CCB05C
2,AACACACGTTGCTTGA-410_B05,AACACACGTTGCTTGA,410_B05,L8TX_201030_01_C12,WMB-10Xv3-HPF,cell,NaN,10Xv3,RHP,Snap25-IRES2-Cre;Ai14-550850,...,018 L2 IT PPP-APr Glut,0082 L2 IT PPP-APr Glut_3,0326 L2 IT PPP-APr Glut_3,#2B93DF,#FA0087,#0F6632,#266DFF,#64661F,15,#CCB05C
3,CACAGATAGAGGCGGA-410_A05,CACAGATAGAGGCGGA,410_A05,L8TX_201029_01_A10,WMB-10Xv3-HPF,cell,NaN,10Xv3,RHP,Snap25-IRES2-Cre;Ai14-550850,...,018 L2 IT PPP-APr Glut,0082 L2 IT PPP-APr Glut_3,0326 L2 IT PPP-APr Glut_3,#2B93DF,#FA0087,#0F6632,#266DFF,#64661F,15,#CCB05C
4,AAAGTGAAGCATTTCG-410_B05,AAAGTGAAGCATTTCG,410_B05,L8TX_201030_01_C12,WMB-10Xv3-HPF,cell,NaN,10Xv3,RHP,Snap25-IRES2-Cre;Ai14-550850,...,018 L2 IT PPP-APr Glut,0082 L2 IT PPP-APr Glut_3,0326 L2 IT PPP-APr Glut_3,#2B93DF,#FA0087,#0F6632,#266DFF,#64661F,15,#CCB05C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4042971,GTGTGAGCAAACGCGA-1350_C05,GTGTGAGCAAACGCGA,1350_C05,L8XR_220728_01_A05,WMB-10XMulti,cell,NaN,10xRSeq_Mult,MB,C57BL6J-641405,...,278 NLL Gata3 Gly-Gaba,1074 NLL Gata3 Gly-Gaba_1,4804 NLL Gata3 Gly-Gaba_1,#820e57,#72195a,#E57300,#a4fcb2,#C7CC7A,25,#CC5CB0
4042972,TTAGCAATCCCTGTTA-1350_C05,TTAGCAATCCCTGTTA,1350_C05,L8XR_220728_01_A05,WMB-10XMulti,cell,NaN,10xRSeq_Mult,MB,C57BL6J-641405,...,157 RN Spp1 Glut,0682 RN Spp1 Glut_1,2761 RN Spp1 Glut_1,#2B93DF,#007200,#FF514D,#BA1FCC,#3DCC44,25,#CC5CB0
4042973,TTTGGCTGTCGCGCAA-1350_C05,TTTGGCTGTCGCGCAA,1350_C05,L8XR_220728_01_A05,WMB-10XMulti,cell,NaN,10xRSeq_Mult,MB,C57BL6J-641405,...,278 NLL Gata3 Gly-Gaba,1076 NLL Gata3 Gly-Gaba_3,4806 NLL Gata3 Gly-Gaba_3,#820e57,#72195a,#E57300,#76CC00,#FF00CA,25,#CC5CB0
4042974,ATCCACCTCACAGACT-1320_B04,ATCCACCTCACAGACT,1320_B04,L8XR_220630_02_B10,WMB-10XMulti,cell,NaN,10xRSeq_Mult,OLF,C57BL6J-625156,...,278 NLL Gata3 Gly-Gaba,1076 NLL Gata3 Gly-Gaba_3,4806 NLL Gata3 Gly-Gaba_3,#820e57,#72195a,#E57300,#76CC00,#FF00CA,13,#FF7373
4042975,TCGTTAGCATTGTCCT-1320_B04,TCGTTAGCATTGTCCT,1320_B04,L8XR_220630_02_B10,WMB-10XMulti,cell,NaN,10xRSeq_Mult,OLF,C57BL6J-625156,...,278 NLL Gata3 Gly-Gaba,1076 NLL Gata3 Gly-Gaba_3,4806 NLL Gata3 Gly-Gaba_3,#820e57,#72195a,#E57300,#76CC00,#FF00CA,13,#FF7373

In [4]:
# df.subclass.unique
dfsub = df[df['subclass']=='007 L2/3 IT CTX Glut'].copy()
dfsub['donor_name'] = dfsub['donor_label'].apply(lambda x: int(x.split('-')[-1]))
dfsub

,cell_label,cell_barcode,barcoded_cell_sample_label,library_label,feature_matrix_label,entity,brain_section_label,library_method,region_of_interest_acronym,donor_label,...,supertype,cluster,neurotransmitter_color,class_color,subclass_color,supertype_color,cluster_color,region_of_interest_order,region_of_interest_color,donor_name
88371,GGAAGTGTCGTCAACA-117_A01,GGAAGTGTCGTCAACA,117_A01,L8TX_190430_01_H08,WMB-10Xv3-Isocortex-1,cell,NaN,10Xv3,MOp,Snap25-IRES2-Cre;Ai14-457909,...,0031 L2/3 IT CTX Glut_3,0116 L2/3 IT CTX Glut_3,#2B93DF,#FA0087,#E9530F,#5C6899,#43992E,1,#179968,457909
93744,AGCGATTGTCCCACGA-480_A04,AGCGATTGTCCCACGA,480_A04,L8TX_210107_01_F09,WMB-10Xv3-Isocortex-1,cell,NaN,10Xv3,VIS,Snap25-IRES2-Cre;Ai14-556846,...,0032 L2/3 IT CTX Glut_4,0118 L2/3 IT CTX Glut_4,#2B93DF,#FA0087,#E9530F,#5C9972,#665C0F,7,#0059CC,556846
105238,TTGAACGGTTAGCGGA-390_D02,TTGAACGGTTAGCGGA,390_D02,L8TX_201015_01_A03,WMB-10Xv3-Isocortex-1,cell,NaN,10Xv3,AI,Snap25-IRES2-Cre;Ai14-546799,...,0031 L2/3 IT CTX Glut_3,0113 L2/3 IT CTX Glut_3,#2B93DF,#FA0087,#E9530F,#5C6899,#4DBDFF,10,#6F9945,546799
112052,CTTTCAACAGTTGGTT-382_A03,CTTTCAACAGTTGGTT,382_A03,L8TX_201008_01_G10,WMB-10Xv3-Isocortex-1,cell,NaN,10Xv3,PL-ILA-ORB,Snap25-IRES2-Cre;Ai14-546763,...,0029 L2/3 IT CTX Glut_1,0104 L2/3 IT CTX Glut_1,#2B93DF,#FA0087,#E9530F,#998817,#660F46,9,#8CCC00,546763
112088,TATTTCGAGGAACGTC-515_A03,TATTTCGAGGAACGTC,515_A03,L8TX_210204_01_G05,WMB-10Xv3-Isocortex-1,cell,NaN,10Xv3,AUD-TEa-PERI-ECT,Snap25-IRES2-Cre;Ai14-562458,...,0032 L2/3 IT CTX Glut_4,0119 L2/3 IT CTX Glut_4,#2B93DF,#FA0087,#E9530F,#5C9972,#1F6623,5,#84FF4D,562458
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3765693,CGTCTACTCAGCACAT-012_A01,CGTCTACTCAGCACAT,012_A01,L8TX_180221_01_H11,WMB-10Xv2-Isocortex-4,cell,NaN,10Xv2,TEa-PERI-ECT,Snap25-IRES2-Cre;Ai14-374159,...,0029 L2/3 IT CTX Glut_1,0107 L2/3 IT CTX Glut_1,#2B93DF,#FA0087,#E9530F,#998817,#3D6566,12,#34CC1F,374159
3765695,GTTAAGCCAGGCTCAC-032_A01,GTTAAGCCAGGCTCAC,032_A01,L8TX_180712_01_E05,WMB-10Xv2-Isocortex-4,cell,NaN,10Xv2,TEa-PERI-ECT,Snap25-IRES2-Cre;Ai14-395342,...,0031 L2/3 IT CTX Glut_3,0113 L2/3 IT CTX Glut_3,#2B93DF,#FA0087,#E9530F,#5C6899,#4DBDFF,12,#34CC1F,395342
3765728,AGGCCACAGCCATCGC-013_C01,AGGCCACAGCCATCGC,013_C01,L8TX_180221_01_D12,WMB-10Xv2-Isocortex-4,cell,NaN,10Xv2,TEa-PERI-ECT,Snap25-IRES2-Cre;Ai14-374160,...,0029 L2/3 IT CTX Glut_1,0107 L2/3 IT CTX Glut_1,#2B93DF,#FA0087,#E9530F,#998817,#3D6566,12,#34CC1F,374160
3891672,AGCAGCCAGTAATCCC-013_C01,AGCAGCCAGTAATCCC,013_C01,L8TX_180221_01_D12,WMB-10Xv2-Isocortex-4,cell,NaN,10Xv2,TEa-PERI-ECT,Snap25-IRES2-Cre;Ai14-374160,...,0029 L2/3 IT CTX Glut_1,0107 L2/3 IT CTX Glut_1,#2B93DF,#FA0087,#E9530F,#998817,#3D6566,12,#34CC1F,374160
3928440,GAAGCAGTCTCGCATC-046_C01,GAAGCAGTCTCGCATC,046_C01,L8TX_180829_01_D09,WMB-10Xv2-Isocortex-4,cell,NaN,10Xv2,AUD,Snap25-IRES2-Cre;Ai14-407906,...,0030 L2/3 IT CTX Glut_2,0110 L2/3 IT CTX Glut_2,#2B93DF,#FA0087,#E9530F,#CC7A8F,#FFEC99,4,#455A99,407906

In [5]:
dfsub.region_of_interest_acronym.unique()

array(['MOp', 'VIS', 'AI', 'PL-ILA-ORB', 'AUD-TEa-PERI-ECT', 'ACA',
       'SS-GU-VISC', 'RSP', 'ENT', 'VIS-PTLp', 'OLF', 'MO-FRP', 'LSX',
       'RHP', 'CTXsp', 'P', 'TEa-PERI-ECT', 'SSp', 'AUD'], dtype=object)

In [40]:
df_donors = df0[['external_donor_name', 'cycle', 'assay', 'sex']]
df_donors

     external_donor_name  cycle  assay sex
0                 352353  Light  10Xv2   M
1                 352356  Light  10Xv2   M
2                 352357  Light  10Xv2   M
3                 355877  Light  10Xv2   M
4                 355878  Light  10Xv2   M
..                   ...    ...    ...  ..
312               613581  Light  10Xv3   F
313               618176  Light  10Xv3   M
314               619870  Light  10Xv3   F
315               621073  Light  10Xv3   M
316               621471  Light  10Xv3   F

[317 rows x 4 columns]

In [41]:
dfsub_join = pd.merge(dfsub, df_donors, left_on='donor_name', right_on='external_donor_name')
dfsub_join

,cell_label,cell_barcode,barcoded_cell_sample_label,library_label,feature_matrix_label,entity,brain_section_label,library_method,region_of_interest_acronym,donor_label,...,subclass_color,supertype_color,cluster_color,region_of_interest_order,region_of_interest_color,donor_name,external_donor_name,cycle,assay,sex
0,GGAAGTGTCGTCAACA-117_A01,GGAAGTGTCGTCAACA,117_A01,L8TX_190430_01_H08,WMB-10Xv3-Isocortex-1,cell,NaN,10Xv3,MOp,Snap25-IRES2-Cre;Ai14-457909,...,#E9530F,#5C6899,#43992E,1,#179968,457909,457909,Light,10Xv3,M
1,TCTATCATCAGGGATG-117_D01,TCTATCATCAGGGATG,117_D01,L8TX_190430_01_G08,WMB-10Xv3-Isocortex-1,cell,NaN,10Xv3,MOp,Snap25-IRES2-Cre;Ai14-457909,...,#E9530F,#CC7A8F,#413D66,1,#179968,457909,457909,Light,10Xv3,M
2,AGGCCACTCATACAGC-117_D01,AGGCCACTCATACAGC,117_D01,L8TX_190430_01_G08,WMB-10Xv3-Isocortex-1,cell,NaN,10Xv3,MOp,Snap25-IRES2-Cre;Ai14-457909,...,#E9530F,#CC7A8F,#413D66,1,#179968,457909,457909,Light,10Xv3,M
3,TAGGAGGCATAACGGG-117_D01,TAGGAGGCATAACGGG,117_D01,L8TX_190430_01_G08,WMB-10Xv3-Isocortex-1,cell,NaN,10Xv3,MOp,Snap25-IRES2-Cre;Ai14-457909,...,#E9530F,#CC7A8F,#413D66,1,#179968,457909,457909,Light,10Xv3,M
4,TCACGCTTCGACGTCG-117_A01,TCACGCTTCGACGTCG,117_A01,L8TX_190430_01_H08,WMB-10Xv3-Isocortex-1,cell,NaN,10Xv3,MOp,Snap25-IRES2-Cre;Ai14-457909,...,#E9530F,#5C6899,#43992E,1,#179968,457909,457909,Light,10Xv3,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172208,GGGCACTAGACAGACC-108_A01,GGGCACTAGACAGACC,108_A01,L8TX_190423_01_D06,WMB-10Xv2-OLF,cell,NaN,10Xv2,OLF,Snap25-IRES2-Cre;Ai14-452715,...,#E9530F,#5C9972,#665C0F,13,#FF7373,452715,452715,Light,10Xv2,F
172209,TACACGATCTCTGAGA-108_A01,TACACGATCTCTGAGA,108_A01,L8TX_190423_01_D06,WMB-10Xv2-OLF,cell,NaN,10Xv2,OLF,Snap25-IRES2-Cre;Ai14-452715,...,#E9530F,#5C9972,#1F6646,13,#FF7373,452715,452715,Light,10Xv2,F
172210,GACGGCTAGTACGACG-021_E02,GACGGCTAGTACGACG,021_E02,L8TX_180406_01_D02,WMB-10Xv2-HPF,cell,NaN,10Xv2,RHP,Snap25-IRES2-Cre;Ai14-381295,...,#E9530F,#CC7A8F,#991E00,15,#CCB05C,381295,381295,Light,10Xv2,F
172211,CTGATAGTCGGATGGA-021_D01,CTGATAGTCGGATGGA,021_D01,L8TX_180406_01_C02,WMB-10Xv2-HPF,cell,NaN,10Xv2,RHP,Snap25-IRES2-Cre;Ai14-381295,...,#E9530F,#CC7A8F,#991E00,15,#CCB05C,381295,381295,Light,10Xv2,F
172212,TACGGATGTGCCTGCA-092_A01,TACGGATGTGCCTGCA,092_A01,L8TX_190214_01_E10,WMB-10Xv2-OLF,cell,NaN,10Xv2,OLF,Snap25-IRES2-Cre;Ai14-441865,...,#E9530F,#5C9972,#665C0F,13,#FF7373,441865,441865,Light,10Xv2,M

In [42]:
dfsub_join.groupby(['region_of_interest_acronym', 'cycle']).size().unstack().fillna(0).astype(int).sort_values('Dark')

cycle                       Dark  Light
region_of_interest_acronym
MOp                            0  29211
P                              0      2
VIS                            0  47171
SSp                            0   8657
TEa-PERI-ECT                   0   8341
AUD                            0   9314
CTXsp                          0     14
LSX                            1      0
RHP                           31     16
ENT                           33    140
OLF                           64    231
PL-ILA-ORB                  1094   7775
AI                          1404   6293
SS-GU-VISC                  1479  10583
MO-FRP                      1481   7887
RSP                         1740   8222
AUD-TEa-PERI-ECT            1843   1454
ACA                         1893   7639
VIS-PTLp                    2006   6194

In [43]:
dfsub1 = dfsub_join[dfsub_join['region_of_interest_acronym']=='VIS']
dfsub1v2 = dfsub_join[dfsub_join['region_of_interest_acronym']=='VIS-PTLp']

print(df.shape)
print(dfsub.shape)
dfsub1.shape, dfsub1v2.shape

(4042976, 28)
(172213, 29)

((47171, 33), (8200, 33))

In [44]:
dfsub1.columns

Index(['cell_label', 'cell_barcode', 'barcoded_cell_sample_label',
       'library_label', 'feature_matrix_label', 'entity',
       'brain_section_label', 'library_method', 'region_of_interest_acronym',
       'donor_label', 'donor_genotype', 'donor_sex', 'dataset_label', 'x', 'y',
       'cluster_alias', 'neurotransmitter', 'class', 'subclass', 'supertype',
       'cluster', 'neurotransmitter_color', 'class_color', 'subclass_color',
       'supertype_color', 'cluster_color', 'region_of_interest_order',
       'region_of_interest_color', 'donor_name', 'external_donor_name',
       'cycle', 'assay', 'sex'],
      dtype='object')

In [45]:
dfsub1.donor_label.unique()

array(['Snap25-IRES2-Cre;Ai14-556846', 'Snap25-IRES2-Cre;Ai14-557707',
       'Snap25-IRES2-Cre;Ai14-365619', 'Snap25-IRES2-Cre;Ai14-355878',
       'Snap25-IRES2-Cre;Ai14-366676', 'Snap25-IRES2-Cre;Ai14-366678',
       'Snap25-IRES2-Cre;Ai14-366292', 'Snap25-IRES2-Cre;Ai14-365617',
       'Snap25-IRES2-Cre;Ai14-355877', 'Snap25-IRES2-Cre;Ai14-365616'],
      dtype=object)

In [46]:
dfsub1.donor_label.unique().shape

(10,)

In [47]:
dfsub1.dataset_label.unique()

array(['WMB-10Xv3', 'WMB-10Xv2'], dtype=object)

In [48]:
# VIS-PTLp
dfsub1v2.groupby(['region_of_interest_acronym', 'cycle']).size().unstack().fillna(0).astype(int).sort_values('Dark')

cycle                       Dark  Light
region_of_interest_acronym
VIS-PTLp                    2006   6194

In [49]:
dfsub1v2.iloc[0]

cell_label                                GCACATAGTTTACGAC-447_B06
cell_barcode                                      GCACATAGTTTACGAC
barcoded_cell_sample_label                                 447_B06
library_label                                   L8TX_201204_01_A02
feature_matrix_label                         WMB-10Xv3-Isocortex-1
entity                                                        cell
brain_section_label                                            NaN
library_method                                               10Xv3
region_of_interest_acronym                                VIS-PTLp
donor_label                           Snap25-IRES2-Cre;Ai14-554815
donor_genotype                Snap25-IRES2-Cre/wt;Ai14(RCL-tdT)/wt
donor_sex                                                        F
dataset_label                                            WMB-10Xv3
x                                                        15.199255
y                                                        -0.647794
cluster_alias                                                  228
neurotransmitter                                              Glut
class                                                01 IT-ET Glut
subclass                                      007 L2/3 IT CTX Glut
supertype                                  0031 L2/3 IT CTX Glut_3
cluster                                    0114 L2/3 IT CTX Glut_3
neurotransmitter_color                                     #2B93DF
class_color                                                #FA0087
subclass_color                                             #E9530F
supertype_color                                            #5C6899
cluster_color                                              #1F6624
region_of_interest_order                                         6
region_of_interest_color                                   #26AEFF
donor_name                                                  554815
external_donor_name                                         554815
cycle                                                        Light
assay                                                        10Xv3
sex                                                              F
Name: 29781, dtype: object

In [51]:

dfsub1v2.groupby(['feature_matrix_label', 'cycle', ]).size().unstack().fillna(0).astype(int).sort_values('Dark')

cycle                  Dark  Light
feature_matrix_label
WMB-10Xv2-Isocortex-1     0    139
WMB-10Xv2-Isocortex-2     0   4189
WMB-10Xv2-Isocortex-3     0     71
WMB-10Xv2-Isocortex-4     0      1
WMB-10Xv3-Isocortex-2   337    323
WMB-10Xv3-Isocortex-1  1669   1471

In [58]:
dfsub1v3 = dfsub1v2[dfsub1v2['assay']=='10Xv3']
dfsub1v3.groupby(['cycle', 'feature_matrix_label', 'donor_name',]).size() #.unstack().fillna(0).astype(int)#.sort_values('Dark')

cycle  feature_matrix_label   donor_name
Dark   WMB-10Xv3-Isocortex-1  553680        697
                              553682        972
       WMB-10Xv3-Isocortex-2  553680        134
                              553682        203
Light  WMB-10Xv3-Isocortex-1  553679        598
                              554815        873
       WMB-10Xv3-Isocortex-2  553679        126
                              554815        197
dtype: int64

# Save Metadata

In [55]:
dfsub1v3.to_csv(fout)