In [1]:
import scanpy as sc
import pandas as pd

In [2]:
%%time
f = '/u/home/f/f7xiesnm/project-zipursky/v1-bb/v1/data/allen_dev_v1/DevVIS_multiome_snRNA_processed.h5ad'
adata = sc.read(f, backed='r')
adata

CPU times: user 433 ms, sys: 158 ms, total: 590 ms
Wall time: 1.11 s

AnnData object with n_obs × n_vars = 200061 × 32285 backed at '/u/home/f/f7xiesnm/project-zipursky/v1-bb/v1/data/allen_dev_v1/DevVIS_multiome_snRNA_processed.h5ad'
    obs: 'Unnamed: 0', 'subcluster_id', 'subcluster_label', 'cluster_label', 'subclass_label', 'class_label', 'subcluster_prob', 'cluster_probability', 'subclass_probability', 'class_probability', 'library_prep', 'roi', 'sex', 'donor_name', 'age_label', 'cellNames'

In [3]:
meta = adata.obs
meta.groupby(['subclass_label', 'age_label']).size().unstack()

age_label,E15.5,E16,E17,E18,P0,P2,P4,P5,P8,P9,P11,P14,P56,P58
subclass_label,,,,,,,,,,,,,,
ABC NN,0,0,5,1,77,18,51,83,88,33,68,402,384,1
Astro-TE NN,7,15,147,116,1006,450,1024,1224,728,304,748,4607,3187,203
BAM NN,5,3,21,13,33,27,32,42,32,5,16,159,24,0
CGE GABA,105,196,511,199,841,198,103,39,4,0,1,9,0,0
CLA-EPd-CTX Car3 Glut,2,6,48,37,246,32,96,43,10,7,16,248,225,73
CR Glut,6,3,30,16,1,0,1,0,0,0,0,0,0,0
Endo NN,99,96,186,87,215,38,153,91,104,13,70,1230,657,38
Glioblast,86,170,644,357,2458,387,340,349,77,8,89,340,110,5
IMN IT,143,383,2430,1393,11973,1895,526,155,4,0,3,23,1,0
IMN nonIT,1142,2211,2101,434,823,35,43,3,0,0,0,10,2,0
IP IT,21,71,248,54,501,11,9,22,8,0,5,16,24,1
IP nonIT,153,335,255,41,183,2,7,4,3,0,3,15,4,0
Immature CR Glut,16,16,43,13,7,0,1,0,0,0,0,0,0,0
L2/3 IT CTX Glut,2,0,18,23,748,856,1722,2395,1305,1324,738,5546,6364,1664
L4/5 IT CTX Glut,2,3,110,146,2370,1018,1366,1905,1093,1484,781,5600,5947,1131
L5 ET CTX Glut,44,150,554,188,2294,630,427,516,185,220,136,1027,1470,325
L5 IT CTX Glut,34,48,271,177,1520,371,626,576,358,381,199,1850,2037,503
L5 NP CTX Glut,5,5,90,65,747,161,232,199,87,79,88,629,597,70
L6 CT CTX Glut,133,296,1173,529,4237,911,1269,1506,519,440,712,3642,3604,788
L6 IT CTX Glut,19,15,181,175,1448,369,502,639,224,269,300,1613,1805,513
L6b CTX Glut,24,49,88,39,345,70,85,84,16,24,61,308,232,40
L6b/CT ENT Glut,23,58,252,161,2314,707,173,56,7,2,7,28,2,0
Lamp5 Gaba,1,2,10,12,58,34,188,214,71,27,59,506,462,67
Lamp5 Lhx6 Gaba,0,0,0,1,0,0,6,7,1,1,7,37,23,3
MGE GABA,299,500,719,199,669,71,10,0,0,0,0,1,1,0
MGE GABA RG,21,94,98,17,86,5,7,6,3,0,1,7,2,0
Microglia NN,25,24,96,43,164,48,93,183,107,16,291,2597,1247,80
NEC,188,300,344,74,21,1,4,1,0,0,0,0,0,0
OPC NN,24,48,321,234,818,318,529,800,426,127,414,2536,897,70
Oligo NN,1,0,6,6,8,2,37,48,16,12,145,1636,2594,104
Peri NN,58,76,126,75,122,12,54,30,31,0,8,250,53,2
Pvalb Gaba,71,106,407,231,1718,645,794,782,270,166,179,1378,1540,278
Pvalb chandelier Gaba,0,0,5,4,77,56,79,74,12,8,4,49,25,4
RG,247,452,364,63,141,3,11,3,2,0,0,3,0,0
SMC NN,0,0,0,1,0,0,0,0,0,0,1,12,2,0
Sncg Gaba,0,4,39,29,232,54,63,46,26,13,14,100,97,31
Sst Chodl Gaba,2,4,31,19,30,8,29,10,4,2,7,25,31,4
Sst Gaba,32,84,253,165,1488,430,494,533,197,187,127,941,959,190
VLMC NN,98,93,388,188,353,153,176,141,136,35,84,556,223,2
Vip Gaba,0,5,11,22,245,113,250,296,144,80,111,644,538,60

In [4]:

meta_it = meta[meta['subclass_label'].str.contains('IT CTX Glut')]
counts = meta_it.groupby(['subclass_label', 'age_label']).size().unstack()
counts = counts[counts.sum(axis=1)>0]
counts

age_label,E15.5,E16,E17,E18,P0,P2,P4,P5,P8,P9,P11,P14,P56,P58
subclass_label,,,,,,,,,,,,,,
L2/3 IT CTX Glut,2,0,18,23,748,856,1722,2395,1305,1324,738,5546,6364,1664
L4/5 IT CTX Glut,2,3,110,146,2370,1018,1366,1905,1093,1484,781,5600,5947,1131
L5 IT CTX Glut,34,48,271,177,1520,371,626,576,358,381,199,1850,2037,503
L6 IT CTX Glut,19,15,181,175,1448,369,502,639,224,269,300,1613,1805,513

In [5]:
counts2 = meta_it.groupby(['cluster_label', 'age_label']).size().unstack()
counts2 = counts2[counts2.sum(axis=1)>0]
counts2

age_label,E15.5,E16,E17,E18,P0,P2,P4,P5,P8,P9,P11,P14,P56,P58
cluster_label,,,,,,,,,,,,,,
37_L6 IT CTX Glut_1,17,14,159,152,1265,331,409,551,190,235,212,326,505,128
41_L6 IT CTX Glut_2,0,0,0,0,0,0,0,0,0,0,42,780,566,170
50_L6 IT CTX Glut_4,0,0,0,0,1,0,0,0,0,0,17,196,267,93
51_L6 IT CTX Glut_4,2,1,22,23,182,38,93,88,34,34,29,304,265,52
52_L6 IT CTX Glut_4,0,0,0,0,0,0,0,0,0,0,0,7,202,70
56_L5 IT CTX Glut_1,7,10,108,68,661,153,306,174,66,72,52,690,448,113
62_L5 IT CTX Glut_3,0,0,3,0,2,0,1,0,0,0,0,58,231,73
63_L5 IT CTX Glut_4,0,0,0,0,0,0,0,0,0,0,0,10,136,54
64_L5 IT CTX Glut_4,27,38,160,109,857,218,319,402,292,309,147,1092,1222,263
68_L4/5 IT CTX Glut_1,0,0,5,0,7,8,15,65,30,54,28,202,428,90
73_L4/5 IT CTX Glut_1,2,2,63,77,739,289,334,473,199,302,170,1142,1035,168
82_L4/5 IT CTX Glut_2,0,0,1,0,2,0,0,1,0,0,1,49,349,107
100_L4/5 IT CTX Glut_6,0,1,41,69,1620,720,1017,1366,864,1128,578,3813,3693,595
101_L4/5 IT CTX Glut_6,0,0,0,0,2,1,0,0,0,0,4,394,442,171
109_L2/3 IT CTX Glut_2,0,0,0,2,8,0,1,0,0,0,41,1084,2307,741
110_L2/3 IT CTX Glut_2,1,0,5,10,393,736,1502,1879,1023,979,458,2660,2038,443
111_L2/3 IT CTX Glut_2,1,0,13,11,339,120,217,512,280,343,167,1177,970,288
116_L2/3 IT CTX Glut_3,0,0,0,0,8,0,2,4,2,2,72,620,618,93
118_L2/3 IT CTX Glut_4,0,0,0,0,0,0,0,0,0,0,0,5,431,99

In [6]:
counts3 = meta_it.groupby(['subcluster_label', 'age_label']).size().unstack()
counts3 = counts3[counts3.sum(axis=1)>0]
counts3.head(134)

age_label,E15.5,E16,E17,E18,P0,P2,P4,P5,P8,P9,P11,P14,P56,P58
subcluster_label,,,,,,,,,,,,,,
37_L6 IT CTX Glut_1_1,0,0,3,2,20,1,0,0,0,0,0,0,0,0
37_L6 IT CTX Glut_1_2,3,2,14,3,13,0,0,0,0,0,0,0,0,0
37_L6 IT CTX Glut_1_3,13,12,135,141,1160,236,1,0,0,0,0,0,0,0
37_L6 IT CTX Glut_1_4,1,0,6,6,56,94,294,468,4,1,0,1,0,0
37_L6 IT CTX Glut_1_5,0,0,0,0,10,0,37,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111_L2/3 IT CTX Glut_2_11,1,0,3,0,4,1,0,0,0,1,0,151,964,287
116_L2/3 IT CTX Glut_3_1,0,0,0,0,3,0,0,0,0,0,0,7,599,93
116_L2/3 IT CTX Glut_3_2,0,0,0,0,5,0,2,4,2,2,72,613,19,0
118_L2/3 IT CTX Glut_4_1,0,0,0,0,0,0,0,0,0,0,0,0,8,1
118_L2/3 IT CTX Glut_4_2,0,0,0,0,0,0,0,0,0,0,0,5,423,98